net: dsa: hms: add driver for HMS switch
This supports Heterogeneous Multi-SoC switch an TSN Ethernet Switch
from i.MX RT1180. one i.MX RT1180 switch port or other ethernet port
is connected to MPU as data path. And, i.MX RT1180 as a SPI deive
from MPU provides contro path.

The driver uses NETC tag driver to rx/tx packets, and SPI transfer
to rx/tx the control command.

Signed-off-by: Minghuan Lian <minghuan.lian@nxp.com>

update the prototype of hooks port_hwtstamp_get/set
The 6c14058edfd0 ("net: dsa: convert to ndo_hwtstamp_get() and ndo_hwtstamp_set()")
changed the prototype of the hooks port_hwtstamp_get/set().

fix build error:
drivers/net/dsa/hms/hms_ptp.c: In function ‘hms_ptp_clock_unregister’:
drivers/net/dsa/hms/hms_ptp.c:469:9: error: implicit declaration of function ‘del_timer_sync’; did you mean ‘dev_mc_sync’? [-Werror=implicit-function-declaration]
  469 |         del_timer_sync(&ptp_data->extts_timer);
      |         ^~~~~~~~~~~~~~

The commit 8fa7292fee5c ("treewide: Switch/rename to timer_delete[_sync]()")
switched del_timer_sync to timer_delete_sync.

Signed-off-by: Hou Zhiqiang <Zhiqiang.Hou@nxp.com>