ecat: fec: fix compile error
drivers/net/ethernet/freescale/fec_ecat.h:527:36: error: ‘FEC_TX_RING_SIZE’ undeclared here (not in a function); did you mean ‘BPF_RB_RING_SIZE’?
  527 |         struct  sk_buff *tx_skbuff[FEC_TX_RING_SIZE];
                                           ^~~~~~~~~~~~~~~~                                                                                                                                23:32:19 [570/1838]
                                           BPF_RB_RING_SIZE                                                                                                                                23:32:19 [569/1838]
drivers/net/ethernet/freescale/fec_ecat.h:550:36: error: ‘FEC_RX_RING_SIZE’ undeclared here (not in a function); did you mean ‘BPF_RB_RING_SIZE’?
  550 |         struct  sk_buff *rx_skbuff[FEC_RX_RING_SIZE];
                                           ^~~~~~~~~~~~~~~~                                                                                                                                23:32:19 [566/1838]
                                           BPF_RB_RING_SIZE                                                                                                                                23:32:19 [565/1838]
drivers/net/ethernet/freescale/fec_ecat.c: In function ‘fec_ecat_recv_from_queue’:
drivers/net/ethernet/freescale/fec_ecat.c:828:33: error: ‘FEC_ENET_RX_FRSIZE’ undeclared (first use in this function); did you mean ‘FEC_ENET_RXF’?
  828 |                                 FEC_ENET_RX_FRSIZE - fep->rx_align,
                                        ^~~~~~~~~~~~~~~~~~                                                                                                                                 23:32:19 [561/1838]
                                        FEC_ENET_RXF                                                                                                                                       23:32:19 [560/1838]
                   t/freescale/fec_ecat.c:828:33: note: each undeclared identifier is reported only once for each function it appears in                                                   23:32:19 [559/1838]
In file included from ./include/linux/skbuff.h:28,
                   om ./include/net/net_namespace.h:43,                                                                                                                                    23:32:19 [557/1838]
                   om ./include/linux/netdevice.h:38,                                                                                                                                      23:32:19 [556/1838]
                   om drivers/net/ethernet/freescale/fec_ecat.c:16:                                                                                                                        23:32:22 [555/1838]
drivers/net/ethernet/freescale/fec_ecat.c: In function ‘fec_enet_free_buffers’:
drivers/net/ethernet/freescale/fec_ecat.c:1950:42: error: ‘FEC_ENET_RX_FRSIZE’ undeclared (first use in this function); did you mean ‘FEC_ENET_RXF’?
 1950 |                                          FEC_ENET_RX_FRSIZE - fep->rx_align,
                                                 ^~~~~~~~~~~~~~~~~~                                                                                                                        23:32:24 [551/1838]
./include/linux/dma-mapping.h:579:67: note: in definition of macro ‘dma_unmap_single’
  579 | #define dma_unmap_single(d, a, s, r) dma_unmap_single_attrs(d, a, s, r, 0)
      |                                                                   ^
drivers/net/ethernet/freescale/fec_ecat.c: In function ‘fec_enet_alloc_buffers’:
drivers/net/ethernet/freescale/fec_ecat.c:2023:46: error: ‘FEC_ENET_RX_FRSIZE’ undeclared (first use in this function); did you mean ‘FEC_ENET_RXF’?
 2023 |                 skb = netdev_alloc_skb(ndev, FEC_ENET_RX_FRSIZE);
      |                                              ^~~~~~~~~~~~~~~~~~
      |                                              FEC_ENET_RXF
drivers/net/ethernet/freescale/fec_ecat.c:2051:46: error: ‘FEC_ENET_TX_FRSIZE’ undeclared (first use in this function); did you mean ‘FEC_ENET_TS_AVAIL’?
 2051 |                 skb = netdev_alloc_skb(ndev, FEC_ENET_TX_FRSIZE);
      |                                              ^~~~~~~~~~~~~~~~~~
      |                                              FEC_ENET_TS_AVAIL
make[6]: *** [scripts/Makefile.build:287: drivers/net/ethernet/freescale/fec_ecat.o] Error 1

Fixes: af062c20970d ("fec_ecat: add fec native driver for raw packet proto")

Signed-off-by: Jony Zhang <jony.zhang@nxp.com>