net: dpaa: ethercat: fix compilation issues caused by kernel upgrade to 6.18.20
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c: In function 'priv_rx_default_dqrr':
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c:368:17: error: too few arguments to function '_dpa_rx'; expected 8, have 7
  368 |                 _dpa_rx(net_dev, portal, priv, percpu_priv, &dq->fd, fq->fqid,
      |                 ^~~~~~~
In file included from /home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c:34:
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_eth.h:403:12: note: declared here
  403 | void __hot _dpa_rx(struct net_device *net_dev,
      |            ^~~~~~~
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c: At top level:
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c:446:38: error: initialization of 'enum qman_cb_dqrr_result (*)(struct qman_portal *, struct qman_fq *, const struct qm_dqrr_entry *, bool,  struct qman_poll_ctx *)' {aka 'enum qman_cb_dqrr_result (*)(struct qman_portal *, struct qman_fq *, const struct qm_dqrr_entry *, _Bool,  struct qman_poll_ctx *)'} from incompatible pointer type 'enum qman_cb_dqrr_result (*)(struct qman_portal *, struct qman_fq *, const struct qm_dqrr_entry *)' [-Wincompatible-pointer-types]
  446 |         .rx_defq = { .cb = { .dqrr = priv_rx_default_dqrr } },
      |                                      ^~~~~~~~~~~~~~~~~~~~
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c:446:38: note: (near initialization for 'private_fq_cbs.rx_defq.cb.dqrr')
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c:341:1: note: 'priv_rx_default_dqrr' declared here
  341 | priv_rx_default_dqrr(struct qman_portal         *portal,
      | ^~~~~~~~~~~~~~~~~~~~
/home/nxf76885/01-Work/real-time-edge/yocto-real-time-edge/bld-ls1028/tmp/work-shared/ls1028ardb/kernel-source/drivers/net/ethernet/freescale/sdk_dpaa/dpaa_ethercat.c:447:38: error: initialization of 'enum qman_cb_dqrr_result (*)(struct qman_portal *, struct qman_fq *, const struct qm_dqrr_entry *, bool,  struct qman_poll_ctx *)' {aka 'enum qman_cb_dqrr_result (*)(struct qman_portal *, struct qman_fq *, const struct qm_dqrr_entry *, _Bool,  struct qman_poll_ctx *)'} from incompatible pointer type 'enum qman_cb_dqrr_result (*)(struct qman_portal *, struct qman_fq *, const struct qm_dqrr_entry *)' [-Wincompatible-pointer-types]
  447 |         .tx_defq = { .cb = { .dqrr = priv_tx_conf_default_dqrr } },
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jony Zhang <jony.zhang@nxp.com>