ecat: enetc: fix compile error issue
drivers/net/ethernet/freescale/enetc_ecat/enetc_ecat.c: In function ‘enetc_bdr_init’:
drivers/net/ethernet/freescale/enetc_ecat/enetc_ecat.c:3580:19: error: ‘NAPINAMSIZ’ undeclared (first use in this function); did you mean ‘IFNAMSIZ’?
 3580 |         char name[NAPINAMSIZ];
      |                   ^~~~~~~~~~
      |                   IFNAMSIZ
drivers/net/ethernet/freescale/enetc_ecat/enetc_ecat.c:3580:19: note: each undeclared identifier is reported only once for each function it appears in
drivers/net/ethernet/freescale/enetc_ecat/enetc_ecat.c:3580:14: warning: unused variable ‘name’ [-Wunused-variable]
 3580 |         char name[NAPINAMSIZ];
      |              ^~~~
make[7]: *** [scripts/Makefile.build:287: drivers/net/ethernet/freescale/enetc_ecat/enetc_ecat.o] Error 1

Fixes: fe434e12a1ba ("codesys: add native enetc_ecat driver")

Signed-off-by: Jony Zhang <jony.zhang@nxp.com>