enetc: enetc_pci_uio: fix compile error issue
drivers/net/ethernet/freescale/enetc/enetc_pci_uio.c: In function ‘enetc4_set_hd_flow_control’:
drivers/net/ethernet/freescale/enetc/enetc_pci_uio.c:239:57: error: ‘PM_CMD_CFG_HD_FCEN’ undeclared (first use in this function); did you mean ‘PM_CMD_CFG_TX_EN’?
  239 |         val = u32_replace_bits(old_val, enable ? 1 : 0, PM_CMD_CFG_HD_FCEN);
      |                                                         ^~~~~~~~~~~~~~~~~~
      |                                                         PM_CMD_CFG_TX_EN
drivers/net/ethernet/freescale/enetc/enetc_pci_uio.c:239:57: note: each undeclared identifier is reported only once for each function it appears in
make[7]: *** [scripts/Makefile.build:287: drivers/net/ethernet/freescale/enetc/enetc_pci_uio.o] Error 1

Fixes: 9fe372aa489f ("net: enetc: add generic enetc_pci_uio driver")

Signed-off-by: Jony Zhang <jony.zhang@nxp.com>